
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author droii
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        //ImageIcon img = new ImageIcon("/resources/icon/tic-tac-toe-icon.png");
        ImageIcon logo = new ImageIcon(getClass().getClassLoader().getResource("./icon/tic-tac-toe-icon.png"));
        this.setIconImage(logo.getImage());
        TicTacToe.setEnableCPU(false);
        TicTacToe.gameStart();
        playerTurn.setText("player " + TicTacToe.getPlayer() + " turn");
    }

    Engine TicTacToe = new Engine();

    private void gameTurn() {
        if (TicTacToe.isEnableCPU()) {
            playerTurn.setText("TicTacToe");

            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    if (TicTacToe.getBoard()[i][j] == 'x') {
                        if (i == 0 && j == 0) {
                            grid1.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 0 && j == 1) {
                            grid2.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 0 && j == 2) {
                            grid3.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 1 && j == 0) {
                            grid4.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 1 && j == 1) {
                            grid5.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 1 && j == 2) {
                            grid6.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 2 && j == 0) {
                            grid7.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 2 && j == 1) {
                            grid8.setIcon(TicTacToe.getICON_X());
                        }

                        if (i == 2 && j == 2) {
                            grid9.setIcon(TicTacToe.getICON_X());
                        }
                    }
                }
            }
        }

        if (TicTacToe.hasWon('o') || TicTacToe.hasWon('x')) {
            TicTacToe.displayBoard();
            playerTurn.setText("player " + TicTacToe.getPlayer() + " won!");
            return;
        }

        playerTurn.setText("player " + TicTacToe.getPlayer() + " turn");
    }

    private void newGame() {
        grid1.setIcon(null);
        grid2.setIcon(null);
        grid3.setIcon(null);
        grid4.setIcon(null);
        grid5.setIcon(null);
        grid6.setIcon(null);
        grid7.setIcon(null);
        grid8.setIcon(null);
        grid9.setIcon(null);

        TicTacToe.gameStart();

        if (TicTacToe.isEnableCPU()) {
            if (TicTacToe.random.nextBoolean()) {
                TicTacToe.cpuPlay();
                gameTurn();
            }
        }
        
        playerTurn.setText("player " + TicTacToe.getPlayer() + " turn");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        playerTurn = new javax.swing.JLabel();
        canvas1 = new javax.swing.JPanel();
        grid1 = new javax.swing.JLabel();
        canvas2 = new javax.swing.JPanel();
        grid2 = new javax.swing.JLabel();
        canvas3 = new javax.swing.JPanel();
        grid3 = new javax.swing.JLabel();
        canvas4 = new javax.swing.JPanel();
        grid4 = new javax.swing.JLabel();
        canvas5 = new javax.swing.JPanel();
        grid5 = new javax.swing.JLabel();
        canvas6 = new javax.swing.JPanel();
        grid6 = new javax.swing.JLabel();
        canvas7 = new javax.swing.JPanel();
        grid7 = new javax.swing.JLabel();
        canvas8 = new javax.swing.JPanel();
        grid8 = new javax.swing.JLabel();
        canvas9 = new javax.swing.JPanel();
        grid9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNewGame = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuVsCPU = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        playerTurn.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        playerTurn.setForeground(new java.awt.Color(204, 204, 204));
        playerTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerTurn.setText("TicTacToe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(playerTurn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        canvas1.setBackground(new java.awt.Color(204, 204, 204));
        canvas1.setPreferredSize(new java.awt.Dimension(130, 130));

        grid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas1Layout = new javax.swing.GroupLayout(canvas1);
        canvas1.setLayout(canvas1Layout);
        canvas1Layout.setHorizontalGroup(
            canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grid1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        canvas1Layout.setVerticalGroup(
            canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grid1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        canvas2.setBackground(new java.awt.Color(204, 204, 204));
        canvas2.setPreferredSize(new java.awt.Dimension(130, 130));

        grid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas2Layout = new javax.swing.GroupLayout(canvas2);
        canvas2.setLayout(canvas2Layout);
        canvas2Layout.setHorizontalGroup(
            canvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas2Layout.setVerticalGroup(
            canvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas3.setBackground(new java.awt.Color(204, 204, 204));
        canvas3.setPreferredSize(new java.awt.Dimension(130, 130));

        grid3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas3Layout = new javax.swing.GroupLayout(canvas3);
        canvas3.setLayout(canvas3Layout);
        canvas3Layout.setHorizontalGroup(
            canvas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas3Layout.setVerticalGroup(
            canvas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas4.setBackground(new java.awt.Color(204, 204, 204));
        canvas4.setPreferredSize(new java.awt.Dimension(130, 130));

        grid4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas4Layout = new javax.swing.GroupLayout(canvas4);
        canvas4.setLayout(canvas4Layout);
        canvas4Layout.setHorizontalGroup(
            canvas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas4Layout.setVerticalGroup(
            canvas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas5.setBackground(new java.awt.Color(204, 204, 204));
        canvas5.setPreferredSize(new java.awt.Dimension(130, 130));

        grid5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas5Layout = new javax.swing.GroupLayout(canvas5);
        canvas5.setLayout(canvas5Layout);
        canvas5Layout.setHorizontalGroup(
            canvas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas5Layout.setVerticalGroup(
            canvas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid5, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas6.setBackground(new java.awt.Color(204, 204, 204));
        canvas6.setPreferredSize(new java.awt.Dimension(130, 130));

        grid6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas6Layout = new javax.swing.GroupLayout(canvas6);
        canvas6.setLayout(canvas6Layout);
        canvas6Layout.setHorizontalGroup(
            canvas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas6Layout.setVerticalGroup(
            canvas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas7.setBackground(new java.awt.Color(204, 204, 204));
        canvas7.setPreferredSize(new java.awt.Dimension(130, 130));

        grid7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas7Layout = new javax.swing.GroupLayout(canvas7);
        canvas7.setLayout(canvas7Layout);
        canvas7Layout.setHorizontalGroup(
            canvas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas7Layout.setVerticalGroup(
            canvas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas8.setBackground(new java.awt.Color(204, 204, 204));
        canvas8.setPreferredSize(new java.awt.Dimension(130, 130));

        grid8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas8Layout = new javax.swing.GroupLayout(canvas8);
        canvas8.setLayout(canvas8Layout);
        canvas8Layout.setHorizontalGroup(
            canvas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas8Layout.setVerticalGroup(
            canvas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        canvas9.setBackground(new java.awt.Color(204, 204, 204));
        canvas9.setPreferredSize(new java.awt.Dimension(130, 130));

        grid9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvas9Layout = new javax.swing.GroupLayout(canvas9);
        canvas9.setLayout(canvas9Layout);
        canvas9Layout.setHorizontalGroup(
            canvas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        canvas9Layout.setVerticalGroup(
            canvas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(canvas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(grid9, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        btnNewGame.setBackground(new java.awt.Color(51, 51, 51));
        btnNewGame.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(204, 204, 204));
        btnNewGame.setText("New Game");
        btnNewGame.setToolTipText("");
        btnNewGame.setBorder(null);
        btnNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNewGame.setFocusPainted(false);
        btnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewGameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(canvas7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(canvas6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(canvas9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(canvas5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(canvas8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jMenu1.setText("Multiplayer");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chat");
        jMenuBar1.add(jMenu2);

        menuVsCPU.setText("Vs CPU");
        menuVsCPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVsCPUMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuVsCPU);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid1MouseClicked
        if (TicTacToe.play(0, 0)) {
            grid1.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid1MouseClicked

    private void grid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid2MouseClicked
        if (TicTacToe.play(0, 1)) {
            grid2.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid2MouseClicked

    private void grid3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid3MouseClicked
        if (TicTacToe.play(0, 2)) {
            grid3.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid3MouseClicked

    private void grid4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid4MouseClicked
        if (TicTacToe.play(1, 0)) {
            grid4.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid4MouseClicked

    private void grid5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid5MouseClicked
        if (TicTacToe.play(1, 1)) {
            grid5.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid5MouseClicked

    private void grid6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid6MouseClicked
        if (TicTacToe.play(1, 2)) {
            grid6.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid6MouseClicked

    private void grid7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid7MouseClicked
        if (TicTacToe.play(2, 0)) {
            grid7.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid7MouseClicked

    private void grid8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid8MouseClicked
        if (TicTacToe.play(2, 1)) {
            grid8.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid8MouseClicked

    private void grid9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid9MouseClicked
        if (TicTacToe.play(2, 2)) {
            grid9.setIcon(TicTacToe.getPlayerIcon());
            gameTurn();
        }
    }//GEN-LAST:event_grid9MouseClicked

    private void btnNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewGameMouseClicked
        newGame();
    }//GEN-LAST:event_btnNewGameMouseClicked

    private void menuVsCPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVsCPUMouseClicked
        JOptionPane.showMessageDialog(this, "CPU Oponent!");
        TicTacToe.setEnableCPU(true);

        newGame();
    }//GEN-LAST:event_menuVsCPUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewGame;
    private javax.swing.JPanel canvas1;
    private javax.swing.JPanel canvas2;
    private javax.swing.JPanel canvas3;
    private javax.swing.JPanel canvas4;
    private javax.swing.JPanel canvas5;
    private javax.swing.JPanel canvas6;
    private javax.swing.JPanel canvas7;
    private javax.swing.JPanel canvas8;
    private javax.swing.JPanel canvas9;
    private javax.swing.JLabel grid1;
    private javax.swing.JLabel grid2;
    private javax.swing.JLabel grid3;
    private javax.swing.JLabel grid4;
    private javax.swing.JLabel grid5;
    private javax.swing.JLabel grid6;
    private javax.swing.JLabel grid7;
    private javax.swing.JLabel grid8;
    private javax.swing.JLabel grid9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuVsCPU;
    private javax.swing.JLabel playerTurn;
    // End of variables declaration//GEN-END:variables
}
